Імпортуємо необхідні бібліотеки

In [ ]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [4]:
a = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [5]:
m = np.zeros((3, 3), dtype=float)

print(m)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [6]:
m = np.random.randint(1, 11, size=(5, 5))

print(m)

[[ 6 10  4  8  6]
 [10  1  2  1  6]
 [ 8  4  8  9  1]
 [ 6  8  2  4  5]
 [ 5 10  5  3  3]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [7]:
m = np.random.random((4,4))

print(m)

[[0.32284197 0.42773457 0.3678532  0.18667559]
 [0.59334798 0.88641082 0.23690249 0.47316411]
 [0.51298807 0.56583975 0.81715269 0.10309038]
 [0.80133995 0.81208392 0.12311058 0.62511141]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [8]:
a = np.random.randint(1, 10, size=5)
b = np.random.randint(1, 10, size=5)

print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
print(np.dot(a, b))

[4 5 1 2 1]
[6 8 3 9 4]
[10 13  4 11  5]
[-2 -3 -2 -7 -3]
[24 40  3 18  4]
89


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [9]:
a = np.random.randint(1, 10, size=7)
b = np.random.randint(1, 10, size=7)

print(a)
print(b)

print(np.dot(a, b))

[3 9 6 9 4 5 2]
[4 4 7 3 4 6 6]
175


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [10]:
a = np.random.randint(1, 10, size=(2, 2))
b = np.random.randint(1, 10, size=(2, 3))

print(a)
print(b)
print(np.dot(a, b))

[[3 9]
 [4 2]]
[[2 4 6]
 [1 8 9]]
[[15 84 99]
 [10 32 42]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [11]:
m = np.random.randint(1, 10, size=(3, 3))

print(m)

m_inv = np.linalg.inv(m)

print(m_inv)

[[9 8 7]
 [8 2 9]
 [5 3 3]]
[[-0.27272727 -0.03896104  0.75324675]
 [ 0.27272727 -0.1038961  -0.32467532]
 [ 0.18181818  0.16883117 -0.5974026 ]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [12]:
m = np.random.random((4, 4))
m_t = m.T
m_t1 = np.transpose(m)

print(m)
print(m_t)
print(m_t1)

[[0.00179849 0.94718167 0.22253215 0.75217974]
 [0.91431052 0.74149609 0.75748893 0.36185808]
 [0.44997965 0.35419664 0.44946778 0.16675294]
 [0.7145812  0.83772964 0.50300732 0.65127005]]
[[0.00179849 0.91431052 0.44997965 0.7145812 ]
 [0.94718167 0.74149609 0.35419664 0.83772964]
 [0.22253215 0.75748893 0.44946778 0.50300732]
 [0.75217974 0.36185808 0.16675294 0.65127005]]
[[0.00179849 0.91431052 0.44997965 0.7145812 ]
 [0.94718167 0.74149609 0.35419664 0.83772964]
 [0.22253215 0.75748893 0.44946778 0.50300732]
 [0.75217974 0.36185808 0.16675294 0.65127005]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [13]:
m = np.random.randint(1, 10, size = (3, 4))
a = np.random.randint(1, 10, size = 4)

print(m)
print(a)
print(np.dot(m, a))

[[2 4 8 2]
 [8 9 1 2]
 [7 8 4 2]]
[6 6 2 4]
[ 60 112 106]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [14]:
m = np.random.random((2, 3))
a = np.random.random(3)

print(m)
print(a)
print(np.dot(m, a)) # можна так
print(m.dot(a)) # на деяких статтях так

[[0.6135871  0.79781941 0.23639329]
 [0.22136912 0.12525937 0.52149576]]
[0.20916688 0.34667273 0.77433468]
[0.58797185 0.49353935]
[0.58797185 0.49353935]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [15]:
m1 = np.random.randint(1, 10, size = (2, 2))
m2 = np.random.randint(1, 10, size = (2, 2))

print(m1)
print(m2)

print(m1 * m2)

[[4 2]
 [5 8]]
[[3 3]
 [9 8]]
[[12  6]
 [45 64]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [16]:
m1 = np.random.randint(1, 10, size = (2, 2))

print(m1)
print(m1.prod())

[[5 9]
 [3 7]]
945


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [17]:
m = np.random.randint(1, 100, size = (5, 5))
print(m)
print(m.sum())

[[32  8 85 41  6]
 [91 10 89  9  2]
 [89 94 41 14 19]
 [15 82 70 13 74]
 [69 55 81 59 92]]
1240


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [18]:
m = np.random.randint(1, 10, size=(4, 4))
n = np.random.randint(1, 10, size=(4, 4))

print(m)
print(n)
print(m - n)

[[5 4 7 2]
 [8 7 9 8]
 [7 2 5 1]
 [5 7 2 7]]
[[6 8 6 6]
 [2 9 2 3]
 [3 7 5 5]
 [2 8 3 8]]
[[-1 -4  1 -4]
 [ 6 -2  7  5]
 [ 4 -5  0 -4]
 [ 3 -1 -1 -1]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [19]:
m = np.random.random((3, 3))
print(m)
a = np.sum(m, axis=1, keepdims=True)
print(a)

[[0.23145433 0.45221202 0.65356879]
 [0.30904844 0.65508606 0.56486092]
 [0.55413419 0.94404219 0.38094653]]
[[1.33723514]
 [1.52899542]
 [1.87912291]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [20]:
m = np.random.randint(1, 5, size=(3, 4))
r = m ** 2

print(m)
print(r)

[[2 2 3 3]
 [1 2 3 2]
 [2 4 2 3]]
[[ 4  4  9  9]
 [ 1  4  9  4]
 [ 4 16  4  9]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [21]:
a = np.random.randint(1, 50, size=(4))
print(a)
b = a ** 0.5
print(b)

[24 48 12 42]
[4.89897949 6.92820323 3.46410162 6.4807407 ]
